services:
  db:
    image: postgres:16
    container_name: saigonride_db
    environment:
      POSTGRES_PASSWORD: "YourStrong@Password123"
      POSTGRES_DB: SaigonRideDB
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  app:
    build: .
    container_name: saigonride_app
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=SaigonRideDB;Username=postgres;Password=YourStrong@Password123
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data: